language: ruby

rvm:
  - 2.1.5
  - 2.2

cache: bundler

addons:
  postgresql: 9.3

services:
- redis

sudo: false

before_script:
- 'RAILS_ENV=test bundle exec rake db:create db:migrate --trace'

notifications:
  irc: "irc.freenode.org#travis"
